### ISSUE TITLE
clippy.js does not work with jQuery 3.1.1, worked fine with 2.2.0

### ISSUE THREAD

**Issue by wschlich** [clippyjs/clippy.js#47]
with jQuery 3.1.1, clippy does not show. chrome dev consle shows:

clippy.min.js:1 Uncaught TypeError: this._el.animate is not a function
    at clippy.Agent.<anonymous> (clippy.min.js:1)
    at e (jquery-3.1.1.slim.min.js:2)
    at clippy.Queue._progressQueue (clippy.min.js:1)
    at clippy.Queue.queue (clippy.min.js:1)
    at clippy.Agent._addToQueue (clippy.min.js:1)
    at clippy.Agent.moveTo (clippy.min.js:1)
    at (index):198
    at Array.j (clippy.min.js:1)
    at i (jquery-3.1.1.slim.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.1.1.slim.min.js:2)

works: https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
doesn't work: https://code.jquery.com/jquery-3.1.1.slim.min.js

**Comment by sagudev** [comment]
Try without slim
https://code.jquery.com/jquery-3.1.1.slim.min.js to https://code.jquery.com/jquery-3.1.1.min.js

**Comment by wschlich** [comment]
Seems to work, thanks!
